### ISSUE TITLE
shell() fails if there aren't exactly 3 slashes in the shell path

### ISSUE THREAD

**Issue by victorz** [ItzAfroBoy/cfetch#2]
for (int i = 0; i < 3; i++)
		strsep(&shell, "/");

This seems to fail when there aren't 3 slashes in the path to my shell. In my case, "/bin/zsh" (Arch Linux).

Proper solution should probably be to use the last piece of the path, rather than the "third". Maybe use something like [basename](https://man.archlinux.org/man/core/man-pages/basename.3.en).

**Comment by ItzAfroBoy** [comment]
Thanks for opening an issue. I am somewhat new to C so thank you for pointing out that basename exists. Ran it on my system and it seems to be working well.
